@startuml
!include <C4/C4_Deployment>
!include <C4/C4_Component>

left to right direction

Deployment_Node(browser, "User's Computer", "Web Browser") {
    Person(user, "User")
    Component(frontend, "Frontend", "Vue, Typescript")
}

Deployment_Node(ott, "OpenTogetherTube", "Docker") {
    Container(balancer, "Balancer", "Rust", "Distributes Load")
    Container(monolith, "Monolith", "Typescript, Javascript", "Manages Rooms")
    SystemDb(postgres, "Postgres", "Persists Users, Rooms")
    SystemDb(redis, "Redis", "Caching, Session Store")
}

Rel(user, frontend, "Uses")
Rel(frontend, balancer, "Uses", "REST API, websockets")
Rel(monolith, postgres, "Read/Write")
Rel(monolith, redis, "Read/Write")
Rel(balancer, monolith, "Manages")

@enduml

