sequenceDiagram
    actor User
    participant L as :LoadBalancer
    participant M as :Monolith
    participant D as Database

    User->>+L: Join room "foo"
    note over L: Balancer sees that the Room is not loaded
    note over L: Balancer selects Monolith with the least number of loaded Rooms
    L->>M: Send Join message
    M->>+D: Query for Room
    D->>-M: Return Room Settings if it exists
    alt Room is in D
        M->>L: Broadcast Room State
        L->>User: Send Room Information
        note over User,M: Connection is proxied
    else Room is not in D
        M->>L: Kick client with not found message
        L->>User: Kick client, Close websocket
        note over User,M: Connection has ended
    end
