classDiagram
    direction BT
    class MonolithDiscoverer {
        <<Trait>>
        +discover()
    }
    ManualMonolithDiscoverer --|> MonolithDiscoverer
    HarnessMonolithDiscoverer --|> MonolithDiscoverer
    FlyMonolithDiscoverer --|> MonolithDiscoverer
    DnsMonolithDiscoverer --|> MonolithDiscoverer

    DnsDiscoveryConfig --o DnsMonolithDiscoverer
    DnsDiscoveryConfig : +u16 monolith_port
    DnsDiscoveryConfig : +Option~String~ dns_server
    DnsDiscoveryConfig : +String query
    DnsDiscoveryConfig : +Option~u64~ polling_duration
    class DnsMonolithDiscoverer{
        +DnsDiscoveryConfig config
        +new(config: DnsDiscoveryConfig)
        +discover()
    }

    FlyDiscoveryConfig --o FlyMonolithDiscoverer
    FlyDiscoveryConfig : +u16 monolith_port
    FlyDiscoveryConfig : +String fly_app
    FlyDiscoveryConfig : +Option~u8~ polling_duration
    class FlyMonolithDiscoverer{
        +FlyDiscoveryConfig config
        +String query
        +new(config: FlyDiscoveryConfig)
        +discover()
    }

    ManualDiscoveryConfig --o ManualMonolithDiscoverer
    ManualDiscoveryConfig : +Vec monoliths
    class ManualMonolithDiscoverer{
        +ManualDiscoveryConfig config
        +new(config: ManualDiscoveryConfig)
        +discover()
    }

    HarnessDiscoveryConfig --o HarnessMonolithDiscoverer
    HarnessDiscoveryConfig : +u16 port
    class HarnessMonolithDiscoverer{
        +HarnessDiscoveryConfig config
        +new(config: HarnessDiscoveryConfig)
        +discover()
    }
