classDiagram
    direction BT
    class MonolithDiscoverer {
        <<Trait>>
        +discover()
    }
    ManualMonolithDiscoverer --|> MonolithDiscoverer
    HarnessMonolithDiscoverer --|> MonolithDiscoverer
    FlyMonolithDiscoverer --|> MonolithDiscoverer
    DNSMonolithDiscoverer --|> MonolithDiscoverer

    DNSDiscoveryConfig --o DNSMonolithDiscoverer
    DNSDiscoveryConfig : +u16 monolith_port
    DNSDiscoveryConfig : +Option~String~ dns_server
    class DNSMonolithDiscoverer{
        +DNSDiscoveryConfig config
        +Option~String~ query
        +new(config: DNSDiscoveryConfig)
        +discover()
    }

    FlyDiscoveryConfig --o FlyMonolithDiscoverer
    FlyDiscoveryConfig : +u16 monolith_port
    FlyDiscoveryConfig : +String fly_app
    class FlyMonolithDiscoverer{
        +FlyDiscoveryConfig config
        +String query
        +new(config: FlyDiscoveryConfig)
        +discover()
    }

    ManualDiscoveryConfig --o ManualMonolithDiscoverer
    ManualDiscoveryConfig : +Vec monoliths
    class ManualMonolithDiscoverer{
        +ManualDiscoveryConfig config
        +new(config: ManualDiscoveryConfig)
        +discover()
    }

    HarnessDiscoveryConfig --o HarnessMonolithDiscoverer
    HarnessDiscoveryConfig : +u16 port
    class HarnessMonolithDiscoverer{
        +HarnessDiscoveryConfig config
        +new(config: HarnessDiscoveryConfig)
        +discover()
    }
