classDiagram
    class PanelPlugin
    class PanelProps~T~ {
        Options options
        data
        ...
    }
    class CorePanel {
        <<component>>
        PanelProps~Options~ props
        systemState
    }
    class GlobalView {
        <<component>>
        systemState
    }
    class RegionView {
        <<component>>
        systemState
    }
    class DataSource


    PanelOptions "1" --* "1" PanelPlugin : Defines UI for
    PanelOptions "1" .. "1" Options : Defines structure of
    PanelProps "1" --> "1" CorePanel : Is input of
    Options "1" *-- "1" PanelProps : wraps
    DataSource "1" --> "1" PanelProps : Feeds
    PanelPlugin "1" *-- "1" CorePanel : Provides
    CorePanel "1" *-- "0..1" GlobalView : Renders
    CorePanel "1" *-- "0..1" RegionView : Renders
