sequenceDiagram
    box Cypress Test
    actor e2e as Mock User
    participant Browser
    participant ott-vis-datasource
    actor Cypress
    end
    
    e2e->>+Browser : mock user visits
    Browser->>-ott-vis-datasource : requests data
    ott-vis-datasource->>+ Cypress: makes outbound request
    ott-vis-datasource-->>Browser : returns data

    note right of ott-vis-datasource: Cypress intercepts request