sequenceDiagram
    box Visualization
    participant Grafana
    participant ott-vis-datasource
    end

    box OpenTogetherTube
    participant ott-collector
    participant Balancer
    end

    ott-collector->>ott-collector: Discover Balancers
    Grafana->>+ott-vis-datasource: Generate Query
    ott-vis-datasource->>+ott-collector: GET /state
    ott-collector->>+Balancer: Send HTTP Requests to Discovered Balancers
    Balancer->>-ott-collector: Receive JSON Data
    ott-collector->>-ott-vis-datasource: SystemState
    ott-vis-datasource->>-Grafana: Return SystemState