sequenceDiagram
    box Visualization
    participant Grafana
    participant ott-vis-datasource
    end

    box OpenTogetherTube
    participant ott-collector
    participant Balancer
    end

    Grafana->>+ott-vis-datasource: Generate Query
    ott-vis-datasource->>+ott-collector: Send HTTP Request
    ott-collector->>+Balancer: Discover and Cache Balancers
    ott-collector->>Balancer: Send HTTP Requests
    Balancer-->>-ott-collector: Recieve JSON Data
    ott-collector-->>-ott-vis-datasource: Honor Fetch Request
    ott-vis-datasource-->>-Grafana: Return JSON Data to Panel