@startuml
node Browser {
  portout http
}

node Balancer  {
  portin "BALANCER_PORT=8081" as BALANCER_PORT
  portout http_proxy
  portout monolith
}

node Monolith0 {
  portin "PORT=3000" as PORT0
  portin "BALANCING_PORT=3002" as BALANCING_PORT0
}

node Monolith1 {
  portin "PORT=3003" as PORT1
  portin "BALANCING_PORT=3004" as BALANCING_PORT1
}

http --> BALANCER_PORT
http_proxy --> PORT0
monolith --> BALANCING_PORT0
http_proxy --> PORT1
monolith --> BALANCING_PORT1

@enduml
