@startuml

skinparam component {
  FontSize 30
  Style rectangle
}
skinparam interface {
  FontSize 20
}

left to right direction
component Browser {
  portout http
}

component Balancer  {
  interface "BALANCER_PORT=8081" as BALANCER_PORT
  portout http_proxy
  portout monolith
}

component Monolith {
  interface "PORT=3000" as PORT
  interface "BALANCING_PORT=3002" as BALANCING_PORT
}

http --> BALANCER_PORT
http_proxy --> PORT
monolith --> BALANCING_PORT

@enduml
