@startuml

skinparam component {
  FontSize 30
  Style rectangle
}
skinparam interface {
  FontSize 20
}

left to right direction
component Browser {
  portout http
}

component Balancer  {
  interface "BALANCER_PORT=8081" as BALANCER_PORT
  portout http_proxy
  portout monolith
}

component Monolith0 {
  interface "PORT=3000" as PORT0
  interface "BALANCING_PORT=3002" as BALANCING_PORT0
}

component Monolith1 {
  interface "PORT=3003" as PORT1
  interface "BALANCING_PORT=3004" as BALANCING_PORT1
}

http --> BALANCER_PORT
http_proxy --> PORT0
monolith --> BALANCING_PORT0
http_proxy --> PORT1
monolith --> BALANCING_PORT1

@enduml
