@startuml

folder "Rust crates" {
  package ott_common [
    Contains common functionality
  ]
  package ott_balancer [
    The Balancer
  ]
  package ott_balancer_bin [
    The Balancer (builds as binary)
  ]
  package ott_balancer_protocol [
    Provides types shared between
    the Balancer and Monolith
  ]
  package harness [
    Provides abstraction around
    integration testing the Balancer
  ]
  package harness_tests [
    Tests the Balancer using harness
  ]
}


ott_balancer --> ott_common : depends
ott_balancer -> ott_balancer_protocol : depends
harness --> ott_balancer_protocol : depends
harness_tests --> harness : depends
harness_tests -> ott_balancer_protocol : depends
harness <.> ott_balancer : connects via websockets
ott_balancer_bin --> ott_balancer : depends

@enduml