C4Component
    Component(api, "REST API", "", "Handles HTTP requests")
    Component(clientman, "Client Manager", "", "Manages Websockets")
    Component(storage, "Storage", "", "Handles Data Persistance")
    Component(roomman, "Room Manager", "", "Manages Rooms")
    Component(infoext, "Info Extractor", "", "Extracts Video Metadata")

    BiRel(roomman, clientman, "Send messages")
    Rel(api, roomman, "Uses")
    Rel(roomman, infoext, "Uses")
    Rel(api, storage, "Uses")
    Rel(roomman, storage, "Uses")
    Rel(infoext, storage, "Uses")

    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
