C4Component
    Component(storage, "Storage", "", "Handles Data Persistance")
    Component(api, "REST API", "", "Handles HTTP requests")
    Component(infoext, "Info Extractor", "", "Extracts Video Metadata")
    Component(roomman, "Room Manager", "", "Manages Rooms")
    Component(clientman, "Client Manager", "", "Manages Websockets")

    BiRel(roomman, clientman, "Send messages")
    Rel(api, roomman, "Uses")
    Rel(roomman, infoext, "Uses")
    Rel(api, storage, "Uses")
    Rel(api, infoext, "Uses")
    Rel(roomman, storage, "Uses")
    Rel(infoext, storage, "Uses")

    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
