sequenceDiagram
    participant L as :LoadBalancer
    participant N as 1:Monolith
    participant M as 2:Monolith
    N->>L: Room "foo" loaded, load_epoch=1
    M->>L: Room "foo" loaded, load_epoch=2
    Note over L,M: Duplicated room puts system in a bad state
    Note over L: Compares load_epoch
    L->>+M: Unload "foo"
    M->>-L: Room unloaded
