flowchart TD
    subgraph Test

    subgraph TestRunner
    DiscoveryProvider
    Balancer
    DiscoveryProvider -- Connects to --> Balancer
    end

    subgraph Clients[Emulated Clients]
    direction LR
    c0[Client 0]
    c1[Client 1]
    cn[...]
    end

    subgraph Monoliths[Emulated Monoliths]
    direction TB
    m0[Monolith 0]
    m1[Monolith 1]
    mn[...]
    end

    Balancer -- Connects to --> Monoliths
    Clients -- Connects to --> Balancer

    Monoliths -- Informs Existence --> DiscoveryProvider
    end
