graph LR
Maintainer((Maintainer of OTT))
Website((OpenTogetherTube.com))

Maintainer -- Hosts --> Fly
Maintainer -- Maintain --> Website
Maintainer -- Manage --> Fly
Fly -- Hosts --> Website
Fly -- Manage --> Website