sequenceDiagram
    actor Alice
    actor John
    participant OTT as OTT website
    participant L as Load Balancer
    participant N as Monolith1
    participant M as Monolith2
    Alice->>+OTT: Join Room "foo".
    OTT->>+L: Take this connection
    Note over L: Instantiates "foo" on a Monolith
    L->>+N: Alice joins "foo"
    John->>+OTT: Join Room "foo".
    OTT->>+L: Take this connection
    Note over L: Instantiates "foo" on a Monolith
    L->>+M: John joins "foo"
    Note over Alice,M: The room "foo" is loaded on two Monoliths and the system is now in a bad state.