sequenceDiagram
    actor Alice
    actor John
    participant OTT as OTT website
    participant L as Load Balancer
    participant M1 as :Monolith 1
    participant M2 as :Monolith 2
    Alice->>+OTT: Join Room "foo".
    OTT->>+L: Take this connection
    Note over L: Instantiates "foo" on a Monolith
    L->>+M1: Alice joins "foo"
    John->>+OTT: Join Room "foo".
    OTT->>+L: Take this connection
    Note over L: Instantiates "foo" on a Monolith
    L->>+M2: John joins "foo"
    Note over Alice,M2: "foo" is loaded on 2 Monoliths.
    Note over Alice,M2: System is in a bad state.