classDiagram
    ManualDiscoveryConfig --o ManualMonolithDiscoverer
    ManualDiscoveryConfig : +Vec monoliths
    class ManualMonolithDiscoverer{
        +ManualDiscoveryConfig config
        +create(config: ManualDiscoveryConfig)
        +discover()
    }