sequenceDiagram
    participant Monolith
    participant Balancer

    Monolith->>Monolith: Generate Monolith ID on startup
    Monolith->>Balancer: Send Monolith ID in Init Message
    Balancer->>Balancer: Receive MonolithId
    Note over Monolith,Balancer: Connection Established
