classDiagram
    direction TB

    class MinRoomsSelector
    class HashRingSelector 

    class MonolithSelection {
        <<trait>>
        select_monolith(room: RoomName, monolith: Vec~BalancerMonolith~) Result~&BalancerMonolith~
        random_monolith(room: RoomName, monolith: Vec~BalancerMonolith~) Result~&BalancerMonolith~

    }

    MonolithSelection <|-- MinRoomsSelector : implements
    MonolithSelection <|-- HashRingSelector : implements

    class BalancerContext {
        clients: HashMap~ClientId-BalancerClient~,
        monoliths: HashMap~MonolithId-BalancerMonolith~,
        rooms_to_monoliths: HashMap~RoomName-MonolithId~,
        monoliths_by_region: HashMap~String-Vec~MonolithId~~,
        monolith_selection: Box~MonolithSelection~
    }

    BalancerContext "1" --> "1" MonolithSelection : calls