stateDiagram-v2
    state "Send init message to balancer" as send
    state "Handle connection initialization" as initialized
    state "Connected" as connected

    [*] --> send: New connection request
    send --> initialized: Init message received
    initialized --> connected: Connection initialized to balancer

    connected --> [*]