@startuml
left to right direction

actor User
actor Friend
rectangle {
  usecase "Create Room"
  usecase "Join Room"
  User --> (Create Room)
  User --> (Get Link)
  (Get Link) --> (Join Room)
  (Create Room) --> (Create Permanent Room) : includes
  (Create Room) --> (Create Temporary Room): includes
  (Create Temporary Room) --> (Share Link)
  (Create Permanent Room) --> (Share Link)
  (Join Room) --> (Share Link)
  (Share Link) --> Friend
  (Join Room) --> (Watch Video)
  (Join Room) --> (Control Playback)
  (Join Room) --> (Manage Queue)
  (Join Room) --> (Manage Room Settings)
  (Manage Room Settings) --> (Manage User Permissions)
}

@enduml
