@startuml
left to right direction
actor "Self-Hoster" as hoster
actor "User" as user
rectangle OTT {
  usecase "Deploy OTT via docker-compose" as UC1
  usecase "Use OTT as end user" as UC2
}
hoster --> UC1
hoster --> user #line.dashed : can also be
user --> UC2
@enduml