@startuml
left to right direction
actor "Self-Hoster" as hoster
actor "User" as user
rectangle OTT {
  usecase "Has Docker Installed" as UC1
  usecase "Has Docker-Compose Installed" as UC1.1
  usecase "Deploy Self-Hosted Instance" as UC1.2
  usecase "Use OTT as end user" as UC2
}
hoster --> UC1
UC1 --> UC1.1 #line.dashed : includes
UC1 --> UC1.2
hoster --> user #line.dashed : can also be
user --> UC2
@enduml