classDiagram
    Balancers <.. ott-vis-datasource : queries
    ott-vis-datasource <.. ott-vis : recieves data from
    ott-vis *-- Panel
    GlobalView <.. Panel : imports
    RegionView <.. Panel : imports
    Latency <.. Panel : imports
    TrafficHeatMap <.. Panel : imports
    UserTraffic <.. Panel : imports