@startuml
[React] <.. [ott-vis]
[TypeScript] <.. [ott-vis]
[ott-vis] - [/components] : contains
[ott-vis] - [module.ts] : contains
[/components] - [Panel.tsx] : contains
[/components] - [ForceGraph.tsx] : contains
[Panel.tsx] <.. [ForceGraph.tsx]
[Panel.tsx] <.. [module.ts]
[ForceGraph.tsx] ..> [D3.js]
@enduml