sequenceDiagram
    Grafana->>+ott-vis-datasource: Generate Query
    ott-vis-datasource->>+ott-vis-collector: Send Fetch Request
    ott-vis-collector->>+HTTP Server: Establish HTTP Server with Rocket
    HTTP Server->>+Balancer: Send HTTP Request
    Balancer-->>+ott-vis-collector: Recieve JSON Data
    ott-vis-collector->>+HTTP Server: Kill Server
    ott-vis-collector-->>+ott-vis-datasource: Honor Fetch Request
    ott-vis-datasource-->>Grafana: Return JSON Data to Panel