name: Figures

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @mermaid-js/mermaid-cli@10.6.1
      - run: sudo apt-get install -y graphviz parallel
      - name: Ensure generated files are up to date
        run: ./scripts/ensure-generated.sh
